version: '3.8'

services:
  app:
    build: .
    container_name: ai-app
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:2.9.2
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml
    ports:
      - "3100:3100"
    restart: always

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log
    restart: always
